[theme]
# base="dark"
# primaryColor="#6c45fe"
# primaryColor="#9c99ff"
# primaryColor="#5215fc"
# primaryColor="#16a68e"
# primaryColor="#2cbfb1"
# primaryColor="#fb9c1b"
# primaryColor="#ff5674"

# base="light"
font="sans serif"
# textColor="#262f40"
primaryColor="#1793a9"
# backgroundColor="#f5f9fa"
backgroundColor="#eff4f7"
secondaryBackgroundColor="#eff4f7"
# secondaryBackgroundColor="#f5f9fa"

# base="dark"
# font="sans serif"
# textColor="#bbbfc7"
# textColor="#f2f3f7"
# textColor="#b4b9c7"
# primaryColor="#3cbcc3"
# backgroundColor="#1a1a1a"
# backgroundColor="#18181c"
# backgroundColor="#101010"
# secondaryBackgroundColor="#262730"
# secondaryBackgroundColor="#18181c"
# secondaryBackgroundColor="#0d0d0d"
