[theme]
# base="dark"
# primaryColor="#6c45fe"
# primaryColor="#9c99ff"
# primaryColor="#5215fc"
# primaryColor="#16a68e"
# primaryColor="#fb9c1b"
# primaryColor="#ff5674"

# textColor="#b4b9c7"
# backgroundColor="#101010"
# secondaryBackgroundColor="#262730"

# base="light"
# font="sans serif"
# textColor="#262f40"
# primaryColor="#ff5674"
primaryColor="#2cbfb1"
backgroundColor="#f5f9fa"
secondaryBackgroundColor="#f5f9fa"

# textColor="#f2f3f7"
# backgroundColor="#18181c"
# secondaryBackgroundColor="#18181c"

# base="dark"
# font="sans serif"
# textColor="#bbbfc7"
# primaryColor="#3cbcc3"
# backgroundColor="#1a1a1a"
# secondaryBackgroundColor="#0d0d0d"
