[theme]
# base="dark"
# primaryColor="#7653fe"
# primaryColor="#16a68e"
# primaryColor="#9ac2ee"
# primaryColor="#e0f501"
# primaryColor="#fb9c1b"

# textColor="#b4b9c7"
# backgroundColor="#101010"
# secondaryBackgroundColor="#262730"
# secondaryBackgroundColor="#919598"

base="light"
font="sans serif"
textColor="#232323"
# primaryColor="#f75105"
# primaryColor="#3cbcc3"
primaryColor="#6c45fe"
backgroundColor="#b4b4b4"
# secondaryBackgroundColor="#cccccc"
# secondaryBackgroundColor="#9f9f9f"
secondaryBackgroundColor="#a9a9a9"


# base="dark"
# textColor="#bbbabf"
# primaryColor="#6799cf"
# backgroundColor="#1c1c1c"
# secondaryBackgroundColor="#0f0f0f"
