[theme]
# base="dark"
# primaryColor="#6c45fe"
# primaryColor="#8a97eb"
# primaryColor="#16a68e"
# primaryColor="#9ac2ee"
# primaryColor="#0b79b4"
# primaryColor="#e0f501"
# primaryColor="#fb9c1b"
# primaryColor="#ff7600"
# primaryColor="#dc143c"

# textColor="#b4b9c7"
# backgroundColor="#101010"
# secondaryBackgroundColor="#262730"
# secondaryBackgroundColor="#919598"

base="light"
font="sans serif"
textColor="#232323"
primaryColor="#6c45fe"
backgroundColor="#ececec"
secondaryBackgroundColor="#f8f8f8"


# base="dark"
# font="sans serif"
# textColor="#a0a7ad"
# primaryColor="#3cbcc3"
# backgroundColor="#1a1a1a"
# secondaryBackgroundColor="#0d0d0d"
